server:
  port: 5051
spring:
  application:
    name:insgatewayservices
  cloud:
    gateway:
      routes:
        - id: 
          uri: lb://CARTSERVICES
          predicates:
            - Path=/cartservices/**
        - id: CARTSERVICES
          uri: lb://PRODUCTSERVICES
          predicates:
            - Path=/productservices/**
         

