spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/msdb
    password: ENC(ujhrZqUzcSrWPmN40oLoOJ19asQt5FER)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
kafka:
  bootstrap:
    server:
      url: localhost:9092
  topic: customerInfo
crmservices:
  getCustomer:
    url: http://GATEWAYSERVICES/insrestgateway/customerservices/customer/getCustomerByID/{customerId}
